Feature/parkings update crud
lmportoesq/parkingapp-back-end pull request #5
Opened 2022-03-29 03:06 UTC by jlopezsa

Crea estructura de archivos para ./api/parkings.
Se implementa el método UPDATE (patch) para Api parkings.

En este PR se completan los métodos GET, GET by ID, POST, DELETE y UPDATE

También se adiciona el archivo template para realizar la descripción de futuros PR

2022-03-31 21:46 UTC, buty619 requested changes
solo un pequeño cambio 🤟

2022-03-31 21:46 UTC, buty619 commented on api/parkings/index.js
>  router.get('/', handlerAllParkings);
creo que lo mejor es que para todas estar rutas especifiquen que se trata de un `parking` dado que cuando inicien con las otras entidades puede generar la confusión entonces manejar los mismos metodos pero  con la ruta `/parkink/:id` o `/parkink`

2022-03-31 22:45 UTC, jlopezsa commented on api/parkings/index.js
>  router.get('/', handlerAllParkings);
Cristian, la palabra parkings la estamos adicionando en el archivo `routes.js` que está en la raiz, como se ve en la imagen
![image](https://user-images.githubusercontent.com/14225699/161161343-6cfb18f2-bf87-427f-b44a-8ec95d782fc0.png)
En ese archivo estaremos adicionando las otras rutas, de los otras entidades, por ejemplo:
`app.use('api/users', users)`

2022-04-01 15:34 UTC, buty619 approved these changes
Ready to merge

2022-04-01 15:35 UTC, merged